### ISSUE TITLE
About the experiment setting

### ISSUE THREAD

**Issue by Gary-code** [guilk/KAT#11]
Hi, very nice work in NAACL 2022. I am quite curious about the computation resource. It seems that you use lots of v100 to train this model. How can I train this with the limited GPU, about just two v100.

**Comment by guilk** [comment]
Hi, thanks for your interest in our work. As far as I remember, we use 16 v100 for each experiment just because they belong to one node.

For the base version, you can train it with two v100s. It should not take a long time to get the results. You can also tweak the number of retrieved descriptions to fit the model into the GPU memory.

For the large version, it may take longer. But the hyper-parameters are very similar to those of the base version. You can simply scale the model without a lot of extra tuning. 

BTW, larger models will help. You should have a much higher number if you use T5-XLarge.

**Comment by CZP686** [comment]
> 嗨，在 NAACL 2022 中做得非常好。我对计算资源很好奇。您似乎使用了很多 v100 来训练此模型。我如何使用有限的 GPU 进行训练，大约只有两个 v100。
Hello, have you trained the model with 2 v100GPUs?
